name: smartmasjid_v1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: ^5.0.6
  graphql_flutter: ^5.2.0-beta.4
  flutter_screenutil: ^5.8.4
  device_preview: ^1.1.0
  intl: any
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  floating_frosted_bottom_bar: ^0.0.1
  step_progress_indicator: ^1.0.2
  dropdown_button2: ^2.1.3
  get_storage: ^2.1.1
  lottie: ^2.4.0
  image_picker: ^0.8.7+5
  country_picker: ^2.0.20
  country_state_picker: ^0.0.4
  country_state_picker_plus: ^1.0.0+1
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  get_cli: ^1.8.3
  image_cropper: any
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  hijri: ^3.0.0
  hijri_picker: ^3.0.0
  table_calendar: ^3.0.9
  flutter_qiblah: ^2.1.0
  location_platform_interface:
  location: ^5.0.0
  cloud_firestore: ^4.8.2
  firebase_messaging: ^14.6.4
  sms_autofill: ^2.3.0
  timer_count_down: ^2.2.2
  google_sign_in: ^6.1.4
  flutter_otp_text_field: ^1.1.1
  flutter_hooks: ^0.18.2
  google_fonts:
  custom_alert_dialog_box: ^1.0.2
  audioplayers: ^4.1.0
  just_audio: ^0.9.34
  auto_size_text: ^3.0.0
  buttons_tabbar: ^1.3.7+1
  easy_date_timeline: ^0.0.6
  flutter_animation_progress_bar: ^2.3.1
  percent_indicator: ^4.2.3
  pie_chart: ^5.3.2
  shared_preferences: ^2.2.0
  flutter_smart_dialog: ^4.9.3+2
  dio: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  qr_code_scanner: ^1.0.1
  dotted_border: ^2.0.0+3
  flutter_native_image: ^0.0.6+1



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  test_api: any
  intl: ^0.18.0
  analyzer: ^5.0.0
  firebase_analytics: ^10.4.4

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/svg/
    - assets/gif/
  uses-material-design: true


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RubikRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RubikRomanSemiBold.ttf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/TimesNewRomanPSBoldMT.ttf
          weight: 700
    - family: Indopak
      fonts:
        - asset: assets/fonts/Indopak.ttf
          weight: 500
    - family: Qalam
      fonts:
        - asset: assets/fonts/Qalam.ttf
          weight: 500
    - family: Quranic
      fonts:
        - asset: assets/fonts/Quranic.ttf
          weight: 500
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
          weight: 500
    - family: Indo
      fonts:
        - asset: assets/fonts/Indo.ttf
          weight: 500
    - family: Uthami
      fonts:
        - asset: assets/fonts/Uthami.ttf
          weight: 500
    - family: Noorehira
      fonts:
        - asset: assets/fonts/Noorehira.ttf
          weight: 500
    - family: Noorehuda
      fonts:
        - asset: assets/fonts/Noorehuda.ttf
          weight: 500
    - family: Noorehidayat
      fonts:
        - asset: assets/fonts/Noorehidayat.ttf
          weight: 500
    - family: Arabictitle
      fonts:
        - asset: assets/fonts/Arabictitle.ttf
          weight: 500
    - family: Arabictit
      fonts:
        - asset: assets/fonts/Arabictit.ttf
          weight: 500

