// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAayOjj7R0iSUdQqLiF-mtwjHHKWBL9XFg',
    appId: '1:231830520319:web:f88cb07b9eebaec353e7ca',
    messagingSenderId: '231830520319',
    projectId: 'smart-masjid-371016',
    authDomain: 'smart-masjid-371016.firebaseapp.com',
    storageBucket: 'smart-masjid-371016.appspot.com',
    measurementId: 'G-3CPGKBGP2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEp25O_n2RkVfTPW8tM0mofplU0tDQtY',
    appId: '1:231830520319:android:3bbd326b044970c453e7ca',
    messagingSenderId: '231830520319',
    projectId: 'smart-masjid-371016',
    storageBucket: 'smart-masjid-371016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGHqdjt17YO0SDBYI7UuL5rsuI0YaNZs',
    appId: '1:231830520319:ios:6c3a32df1a7c7a6a53e7ca',
    messagingSenderId: '231830520319',
    projectId: 'smart-masjid-371016',
    storageBucket: 'smart-masjid-371016.appspot.com',
    androidClientId: '231830520319-q84mprlfsv13ugujsg62l4k6hvtocg6b.apps.googleusercontent.com',
    iosClientId: '231830520319-0mktse2alomr7vp1esiid7dpuu44m9uo.apps.googleusercontent.com',
    iosBundleId: 'com.safatech.ummati',
  );
}
