// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGXuKZa9laM9gIL67K5cpRuPNiJ0y-yQ',
    appId: '1:1049767581944:web:34bfb050d405f44db1c30d',
    messagingSenderId: '1049767581944',
    projectId: 'smasjid-v1',
    authDomain: 'smasjid-v1.firebaseapp.com',
    storageBucket: 'smasjid-v1.appspot.com',
    measurementId: 'G-SKXE870NSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZBn1xzcEwk-5PK89AK5GJ99RYT8_Y7To',
    appId: '1:1049767581944:android:eb5449ab082549f0b1c30d',
    messagingSenderId: '1049767581944',
    projectId: 'smasjid-v1',
    storageBucket: 'smasjid-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHF5ZuUbxpy_2ej55DJ5DngGlkVdpKA6E',
    appId: '1:1049767581944:ios:42aa80fa14917e5fb1c30d',
    messagingSenderId: '1049767581944',
    projectId: 'smasjid-v1',
    storageBucket: 'smasjid-v1.appspot.com',
    iosClientId: '1049767581944-o0emqcos4aoqg7c8nej94bhojpke9oqi.apps.googleusercontent.com',
    iosBundleId: 'com.safatech.smartmasjidV1',
  );
}
