part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const LANGUAGE_PAGE = _Paths.LANGUAGE_PAGE;
  static const REGISTER_LOGIN = _Paths.REGISTER_LOGIN;
  static const SIGNUP_PAGE = _Paths.SIGNUP_PAGE;
  static const FACE_AUTH = _Paths.FACE_AUTH;
  static const OTP_PAGE = _Paths.OTP_PAGE;
  static const LOGIN_PAGE = _Paths.LOGIN_PAGE;
  static const MASJID_FINDER = _Paths.MASJID_FINDER;
  static const ZAKATHPAGE = _Paths.ZAKATHPAGE;
  static const NOTIFICATIONPAGE = _Paths.NOTIFICATIONPAGE;
  static const WEATHERPAGE = _Paths.WEATHERPAGE;
  static const MESSAGEPAGE = _Paths.MESSAGEPAGE;
  static const SETTINGSPAGE = _Paths.SETTINGSPAGE;
  static const QURANPAGE = _Paths.QURANPAGE;
  static const QIBLAFINDERPAGE = _Paths.QIBLAFINDERPAGE;
  static const PRAYERPAGE = _Paths.PRAYERPAGE;
  static const SPECIALDAYSPAGE = _Paths.SPECIALDAYSPAGE;
  static const HIJRIPAGE = _Paths.HIJRIPAGE;
  static const ARCHIVEPAGE = _Paths.ARCHIVEPAGE;
  static const WEATHERLOCATION = _Paths.WEATHERLOCATION;
  static const ADDWEATHER = _Paths.ADDWEATHER;
  static const SLIDERDOT = _Paths.SLIDERDOT;
  static const SINGLEWEATHER = _Paths.SINGLEWEATHER;
  static const PRAYERDETAILSPAGE = _Paths.PRAYERDETAILSPAGE;
  static const PINPUTS = _Paths.PINPUTS;
  static const MASJID_REQUEST = _Paths.MASJID_REQUEST;
  static const MASJIDHISTORY = _Paths.MASJIDHISTORY;
  static const PROFILE_PAGE = _Paths.PROFILE_PAGE;
  static const AUDIOPLAYER = _Paths.AUDIOPLAYER;
  static const IMAN_TRACKER = _Paths.IMAN_TRACKER;
  static const DUAPAGE = _Paths.DUAPAGE;
  static const HADITHCHAPTERDETAIL = _Paths.HADITHCHAPTERDETAIL;
  static const EDITPROFILE = _Paths.EDITPROFILE;
  static const WEATHERDETAIL = _Paths.WEATHERDETAIL;
  static const MEMBERSHIP = _Paths.MEMBERSHIP;
  static const EVENTS = _Paths.EVENTS;
  static const DONATIONPAGE = _Paths.DONATIONPAGE;
  static const MYMASJIDPAGE = _Paths.MYMASJIDPAGE;
  static const SERVICEPAGE = _Paths.SERVICEPAGE;
  static const LIBRARYPAGE = _Paths.LIBRARYPAGE;
  static const MASJIDNEARME = _Paths.MASJIDNEARME;
  static const MEDIAPAGE = _Paths.MEDIAPAGE;
  static const BOOKMARKPAGE = _Paths.BOOKMARKPAGE;
  static const ACTIVITIESPAGE = _Paths.ACTIVITIESPAGE;
  static const FAMILYTREE = _Paths.FAMILYTREE;
  static const GUESTMODE = _Paths.GUESTMODE;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH_SCREEN = '/splash-screen';
  static const LANGUAGE_PAGE = '/language-page';
  static const REGISTER_LOGIN = '/register-login';
  static const SIGNUP_PAGE = '/signup-page';
  static const FACE_AUTH = '/face-auth';
  static const OTP_PAGE = '/otp-page';
  static const LOGIN_PAGE = '/login-page';
  static const MASJID_FINDER = '/masjid-finder';
  static const ZAKATHPAGE = '/zakathpage';
  static const NOTIFICATIONPAGE = '/notificationpage';
  static const WEATHERPAGE = '/weatherpage';
  static const MESSAGEPAGE = '/messagepage';
  static const SETTINGSPAGE = '/settingspage';
  static const QURANPAGE = '/quranpage';
  static const QIBLAFINDERPAGE = '/qiblafinderpage';
  static const PRAYERPAGE = '/prayerpage';
  static const SPECIALDAYSPAGE = '/specialdayspage';
  static const HIJRIPAGE = '/hijripage';
  static const ARCHIVEPAGE = '/archivepage';
  static const WEATHERLOCATION = '/weatherlocation';
  static const ADDWEATHER = '/addweather';
  static const SLIDERDOT = '/sliderdot';
  static const SINGLEWEATHER = '/singleweather';
  static const PRAYERDETAILSPAGE = '/prayerdetailspage';
  static const PINPUTS = '/pinputs';
  static const MASJID_REQUEST = '/masjid-request';
  static const MASJIDHISTORY = '/masjidhistory';
  static const PROFILE_PAGE = '/profile-page';
  static const AUDIOPLAYER = '/audioplayer';
  static const IMAN_TRACKER = '/iman-tracker';
  static const DUAPAGE = '/duapage';
  static const HADITHCHAPTERDETAIL = '/hadithchapterdetail';
  static const EDITPROFILE = '/editProfile';
  static const WEATHERDETAIL = '/weatherdetail';
  static const MEMBERSHIP = '/membership';
  static const EVENTS = '/events';
  static const DONATIONPAGE = '/donationpage';
  static const MYMASJIDPAGE = '/mymasjidpage';
  static const SERVICEPAGE = '/servicepage';
  static const LIBRARYPAGE = '/librarypage';
  static const MASJIDNEARME = '/masjidnearme';
  static const MEDIAPAGE = '/mediapage';
  static const BOOKMARKPAGE = '/bookmarkpage';
  static const ACTIVITIESPAGE = '/activitiespage';
  static const FAMILYTREE = '/familytree';
  static const GUESTMODE = '/guestmode';
}
